version: "3.2"
services:
  stef_db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: stef1234
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
