/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Stef kanban
 * Een mooie beschrijving
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export interface Card {
  taskName: string;
  laneId: string;
  taskDescription: string;
  taskPriority: number;
  user: User;
  id: string;
}
