/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Stef kanban
 * Een mooie beschrijving
 * OpenAPI spec version: 1.0
 */

export interface Lane {
  id: string;
  lane: string;
  createdAt: string;
  updatedAt: string;
}
