/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Stef kanban
 * Een mooie beschrijving
 * OpenAPI spec version: 1.0
 */

export interface User {
  id: string;
  name: string;
  lastname: string;
}
